### ISSUE TITLE
Exception: 'str' object has no attribute 'decode' (pyjwt 2.0.0)

### ISSUE THREAD

**Issue by oldnapalm** [zoffline/zwift-offline#108]
After updating pyjwt from 1.7.1 to 2.0.0 I'm getting this error

```
    refresh_token = jwt.encode(refresh_token, 'nosecret').decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
Exception: 'str' object has no attribute 'decode'
```

Removing `.decode('utf-8')` seems to fix it https://github.com/oldnapalm/zwift-offline/commit/daffd564002db142abc516dd71c222b6ff9b0942

But then it causes error with pyjwt 1.7.1

```
jwt.exceptions.DecodeError: Invalid header padding
Exception: Invalid header padding
```

**Comment by zoffline** [comment]
Thanks! Pushed the fix, but kept backward compatibility to not break any existing installs and maintain Python 2 support.
